<template>
    <navbar />
    <router-view v-slot="{ Component }">
        <transition name="fade" mode="out-in">
            <component :is="Component" />
        </transition>
    </router-view>
    <!-- <router-view></router-view> -->
</template>

<script>
import { mapGetters } from "vuex";
import Navbar from "../components/Navbar.vue";
import { myWebsocket } from "../sockets";

export default {
    name: "main-view",
    components: {
        Navbar,
    },
    computed: {
        ...mapGetters("auth", ["GET_USER_ID"]),
        // ...mapGetters("messenger", ["GET_CONVO_HASHES"]),
        ...mapGetters("messenger", [
            "GET_SOCKET_STATE",
            "GET_CONVO_HASHES",
            "LIST_CONVERSATIONS",
        ]),
    },
    watch: {
        GET_SOCKET_STATE(value) {
            if (value === WebSocket.OPEN) {
                myWebsocket.sendMessage(
                    JSON.stringify({
                        event: "joinAndLeave",
                        data: {
                            userId: Number(this.GET_USER_ID),
                            message: "Hello",
                            meta: "join",
                            room: "#12",
                            rooms: [...this.GET_CONVO_HASHES],
                        },
                    })
                );
            }
        },
    },
    created() {
        myWebsocket.connect();
    },
};
</script>

<style>
/* ----------------------------------------------
 * Generated by Animista on 2021-6-8 20:26:27
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
.slide-trans-enter-from {
    transform: translateX(100%);
}

.slide-trans-enter-to {
    transform: translateX(0%);
}

.slide-trans-enter-active {
    transition: transform 1s ease;
}
</style>
