<template>
    <div
        class="fixed w-full z-20 top-0 left-0 flex items-center justify-center"
    >
        <transition name="snack">
            <div
                class="mt-14 px-5 py-3 bg-yellow-400 flex items-center justify-center rounded-sm shadow-lg text-white text-lg"
                v-if="snack"
            >
                Receiving Call from {{ snack.username }}
                <b-button @click="acceptCall" class="vibrate-1 mx-4"
                    >Accept</b-button
                >
                <b-button @click="declineCall">Decline</b-button>
            </div>
        </transition>
    </div>
</template>

<script>
import { mapActions, mapGetters } from "vuex";
import BButton from "./BButton.vue";
export default {
    components: { BButton },
    name: "call-snack-bar",
    computed: {
        ...mapGetters({
            snack: "callSnack/snack",
        }),
    },
    methods: {
        ...mapActions({
            changeSnack: "callSnack/snack",
        }),
        ...mapActions("messenger", ["SET_ACTIVE_AND_SHOW"]),
        acceptCall() {
            this.SET_ACTIVE_AND_SHOW({ conversation_hash: this.snack.room });
            this.changeSnack(null);
            this.$router.push({ name: "Messenger" });
        },
        declineCall() {
            this.changeSnack(null);
        },
    },
};
</script>

<style scoped>
.snack-enter-active,
.snack-leave-active {
    @apply transition duration-500 ease-in-out;
}

.snack-enter-from {
    @apply transform -translate-y-28;
}

.snack-leave-to {
    @apply transform -translate-y-28;
}

.vibrate-1 {
    -webkit-animation: vibrate-1 0.3s linear infinite both;
    animation: vibrate-1 0.3s linear infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-7-2 14:37:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-1
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-1 {
    0% {
        -webkit-transform: translate(0);
        transform: translate(0);
    }
    20% {
        -webkit-transform: translate(-2px, 2px);
        transform: translate(-2px, 2px);
    }
    40% {
        -webkit-transform: translate(-2px, -2px);
        transform: translate(-2px, -2px);
    }
    60% {
        -webkit-transform: translate(2px, 2px);
        transform: translate(2px, 2px);
    }
    80% {
        -webkit-transform: translate(2px, -2px);
        transform: translate(2px, -2px);
    }
    100% {
        -webkit-transform: translate(0);
        transform: translate(0);
    }
}
@keyframes vibrate-1 {
    0% {
        -webkit-transform: translate(0);
        transform: translate(0);
    }
    20% {
        -webkit-transform: translate(-2px, 2px);
        transform: translate(-2px, 2px);
    }
    40% {
        -webkit-transform: translate(-2px, -2px);
        transform: translate(-2px, -2px);
    }
    60% {
        -webkit-transform: translate(2px, 2px);
        transform: translate(2px, 2px);
    }
    80% {
        -webkit-transform: translate(2px, -2px);
        transform: translate(2px, -2px);
    }
    100% {
        -webkit-transform: translate(0);
        transform: translate(0);
    }
}
</style>
